'use client';

import { useState, useRef } from 'react';
import Image from 'next/image';
import { upload } from '@vercel/blob/client';
import type { PutBlobResult } from '@vercel/blob';

export default function HomePage() {
  const inputFileRef = useRef<HTMLInputElement>(null);
  const [prompt, setPrompt] = useState('');
  const [blob, setBlob] = useState<PutBlobResult | null>(null);
  const [imageUrl, setImageUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!blob) {
      setError('Please upload an image first.');
      return;
    }
    setLoading(true);
    setError('');
    setImageUrl('');

    try {
      const response = await fetch('/api/replicate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt, imageUrl: blob.url }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ error: `HTTP error! status: ${response.status}` }));
        throw new Error(errorData.error || `HTTP error! status: ${response.status}`);
      }

      const data = await response.json();
      if (data && data.length > 0) {
        setImageUrl(data[0]);
      } else {
        setError('No image was generated. Please try again.');
      }
    } catch (err) {
      if (err instanceof Error) {
        setError(`Failed to generate image: ${err.message}`);
      } else {
        setError('An unknown error occurred.');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleFileChange = async (event: React.ChangeEvent<HTMLInputElement>) => {
    event.preventDefault();
    const file = event.currentTarget.files?.[0];
    if (!file) {
      setError("No file selected.");
      return;
    }

    setLoading(true);
    setError('');

    try {
        const newBlob = await upload(file.name, file, {
            access: 'public',
            handleUploadUrl: '/api/upload',
        });
        setBlob(newBlob);
    } catch (err) {
        if (err instanceof Error) {
            setError(`Failed to upload image: ${err.message}`);
        } else {
            setError('An unknown error occurred during upload.');
        }
    } finally {
        setLoading(false);
    }
  };


  return (
    <main className="mx-auto flex min-h-screen max-w-xl flex-col items-center p-24">
      <h1 className="text-center text-4xl font-bold">
        Image-to-Image Playground
      </h1>
      <p className="mt-4 text-center text-lg text-gray-500">
        Upload an image and use a text prompt to modify it.
      </p>

      <div className="mt-8 w-full">
        <label htmlFor="image-upload" className="block text-sm font-medium text-gray-700">
          Upload Image
        </label>
        <input
          id="image-upload"
          name="image-upload"
          type="file"
          required
          ref={inputFileRef}
          onChange={handleFileChange}
          className="mt-1 block w-full text-sm text-gray-500 file:mr-4 file:rounded-md file:border-0 file:bg-gray-100 file:px-4 file:py-2 file:text-sm file:font-semibold hover:file:bg-gray-200"
          disabled={loading}
        />
      </div>

      {blob && (
        <div className="mt-8">
          <h2 className="text-xl font-semibold">Image Preview:</h2>
          <img
            src={blob.url}
            alt="Image preview"
            className="mt-4 rounded-md"
            style={{ maxWidth: '100%', maxHeight: '400px' }}
          />
        </div>
      )}

      <form className="mt-8 flex w-full" onSubmit={handleSubmit}>
        <input
          type="text"
          className="flex-grow rounded-l-md border border-gray-300 p-2 focus:border-black focus:outline-none focus:ring-0"
          placeholder="Enter a prompt to modify the image..."
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          disabled={loading || !blob}
        />
        <button
          type="submit"
          className="rounded-r-md bg-black px-4 py-2 text-white"
          disabled={loading || !blob}
        >
          {loading ? 'Generating...' : 'Generate'}
        </button>
      </form>

      {error && (
        <div className="mt-8 w-full rounded-md border border-red-400 bg-red-100 p-4 text-red-700">
          {error}
        </div>
      )}

      {imageUrl && (
        <div className="mt-8">
          <h2 className="text-xl font-semibold">Generated Image:</h2>
          <Image
            src={imageUrl}
            alt="Generated by Replicate"
            width={512}
            height={512}
            className="mt-4 rounded-md"
          />
        </div>
      )}
    </main>
  );
}
