'use client';

import { useState } from 'react';
import Image from 'next/image';

export default function HomePage() {
  const [prompt, setPrompt] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    setImageUrl('');

    try {
      const response = await fetch('/api/replicate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt }),
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      const data = await response.json();
      if (data && data.length > 0) {
        setImageUrl(data[0]);
      } else {
        setError('No image was generated. Please try again.');
      }
    } catch (err) {
      if (err instanceof Error) {
        setError(`Failed to generate image: ${err.message}`);
      } else {
        setError('An unknown error occurred.');
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="mx-auto flex min-h-screen max-w-xl flex-col items-center p-24">
      <h1 className="text-center text-4xl font-bold">
        Replicate Playground Clone
      </h1>
      <p className="mt-4 text-center text-lg text-gray-500">
        Generate images with the{' '}
        <code className="rounded bg-gray-100 p-1 font-mono text-sm">
          black-forest-labs/flux-kontext-pro
        </code>{' '}
        model.
      </p>

      <form className="mt-8 flex w-full" onSubmit={handleSubmit}>
        <input
          type="text"
          className="flex-grow rounded-l-md border border-gray-300 p-2 focus:border-black focus:outline-none focus:ring-0"
          placeholder="Enter a prompt..."
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          disabled={loading}
        />
        <button
          type="submit"
          className="rounded-r-md bg-black px-4 py-2 text-white"
          disabled={loading}
        >
          {loading ? 'Generating...' : 'Generate'}
        </button>
      </form>

      {error && (
        <div className="mt-8 w-full rounded-md border border-red-400 bg-red-100 p-4 text-red-700">
          {error}
        </div>
      )}

      {imageUrl && (
        <div className="mt-8">
          <h2 className="text-xl font-semibold">Generated Image:</h2>
          <Image
            src={imageUrl}
            alt="Generated by Replicate"
            width={512}
            height={512}
            className="mt-4 rounded-md"
          />
        </div>
      )}
    </main>
  );
}
